
IntroduÃ§Ã£o
Navegando pelo GitHub vocÃª jÃ¡ encontrou perfis incrÃ­veis como esse?

Perfil Github da Jeniffer Bittencourt, usuÃ¡rio jeniblodev, iniciando com o nome dela como tÃ­tulo, seguido de sÃ­mbolos de redes sociais em nuvens, sendo elas instagram, twitter e linkedln. No canto direito Ã© possÃ­vel notar um avatar que representa a imagem dela e no canto esquerdo a Foto de Perfil em formato redondo. Em seguida, Ã© apresentado um texto com a entrada â€œHello, devs!â€ com uma breve apresentaÃ§Ã£o dela, tendo abaixo um gif de um gato digitando em um notebook. ApÃ³s isso, Ã© apresentado as Tecnologias e ferramentas que ela conhece, o mesmo avatar citado anteriormente em outra pose. E por fim, Ã© visto quadros com informaÃ§Ãµes grÃ¡ficas sobre o perfil dela.
Perfil GitHub da Alura Star, Jeniffer Bittencourt: jeniblodev.

Bacana, nÃ£o Ã© mesmo!? Tem curiosidade de como fazer um? EntÃ£o segue um passo a passo de como vocÃª pode montar o seu e algumas dicas!

Banner da Escola de ProgramaÃ§Ã£o: Matricula-se na escola de ProgramaÃ§Ã£o. Junte-se a uma comunidade de mais de 500 mil estudantes. Na Alura vocÃª tem acesso a todos os cursos em uma Ãºnica assinatura; tem novos lanÃ§amentos a cada semana; desafios prÃ¡ticos. Clique e saiba mais!
Como tornar um arquivo README em seu perfil
Um README Ã© um arquivo com extensÃ£o md, ou seja, ele Ã© escrito em Markdown. Para mais informaÃ§Ãµes sobre, dÃª uma olhadinha nos nossos artigos: Como trabalhar com Markdown e Como escrever um bom README.

Para que ele seja visto como seu perfil, Ã© preciso criar um repositÃ³rio pÃºblico com o seu nome de usuÃ¡rio.

Para isso, em Repositories, selecione a opÃ§Ã£o em verde New para criar um novo repositÃ³rio:

Tela Repositories do GitHub do usuÃ¡rio camilafernanda, com destaque na opÃ§Ã£o New no canto superior direito.
Sendo assim, na nova pÃ¡gina que irÃ¡ abrir, chamada Create a new repository, Ã© preciso fazer os seguintes passos:

Em Repository name, coloque o seu nome de usuÃ¡rio. SerÃ¡ utilizado neste exemplo o usuÃ¡rio camilafernanda2. Note que ao fazer isso, o Git mostra uma mensagem especial:
â€œYou found a secret! camilafernanda2/camilafernanda2 is a âœ¨ special âœ¨ repository that you can use to add a README.md to your GitHub profile. Make sure itâ€™s public and initialize it with a README to get started.â€

TraduÃ§Ã£o: VocÃª encontrou um segredo! camilafernanda2/camilafernanda2 Ã© um repositÃ³rio âœ¨ especial âœ¨ que vocÃª pode usar para adicionar um README.md ao seu perfil do GitHub. Certifique-se de que seja pÃºblico e inicialize-o com um README para comeÃ§ar.

Dessa forma, selecione a opÃ§Ã£o Public, para tornar o repositÃ³rio pÃºblico para ser exibido no seu perfil;

Por fim, selecione Add a README file para adicionar este famoso arquivo feito na linguagem de marcaÃ§Ã£o Markdown e, para finalizar, clique em Create repository.

Imagem da pÃ¡gina â€œCreate a new repositoryâ€ citada acima, onde estÃ¡ em destaque a caixa de texto Repository name preenchida com o nome â€œcamilafernanda2â€, alÃ©m disso, estÃ£o em destaque as opÃ§Ãµes â€œPublicâ€ (com um sÃ­mbolo de livro), â€œAdd a README fileâ€ e no botÃ£o â€œCreate repositoryâ€.
Agora Ã© editar o arquivo para deixÃ¡-lo a sua cara. Para isso, clique no Ã­cone de lÃ¡pis no canto superior direito do README.md.

Arquivo README.md no repositÃ³rio camilafernanda2/camilafernanda2 no GitHub, com destaque no Ã­cone de lÃ¡pis no canto superior direito do arquivo.
O arquivo jÃ¡ estarÃ¡ preenchido com o seguinte texto:

## Hi there ğŸ‘‹

<!--
**camilafernanda2/camilafernanda2** is a âœ¨ _special_ âœ¨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- ğŸ”­ Iâ€™m currently working on ...
- ğŸŒ± Iâ€™m currently learning ...
- ğŸ‘¯ Iâ€™m looking to collaborate on ...
- ğŸ¤” Iâ€™m looking for help with ...
- ğŸ’¬ Ask me about ...
- ğŸ“« How to reach me: ...
- ğŸ˜„ Pronouns: ...
- âš¡ Fun fact: ...
-->
TraduÃ§Ã£o:

## OlÃ¡ pessoal ğŸ‘‹

<! --
**camilafernanda2/camilafernanda2** Ã© um repositÃ³rio âœ¨ _especial_ âœ¨ porque seu `README.md` (este arquivo) aparece em seu perfil GitHub.

Aqui estÃ£o algumas idÃ©ias para vocÃª comeÃ§ar:

- ğŸ”­ Atualmente estou trabalhando em ...
- ğŸŒ± Atualmente estou aprendendo ...
- ğŸ‘¯ Estou procurando colaborar em ...
- ğŸ¤” Estou procurando ajuda com ...
- ğŸ’¬ Pergunte-me sobre ...
- ğŸ“« Como entrar em contato comigo: ...
- ğŸ˜„ Pronomes: ...
- âš¡ Curiosidade: ...
-->
O Git ressalta muito bem que este Ã© um repositÃ³rio especial e oferece algumas dicas. AlÃ©m disso, neste documento, vocÃª irÃ¡ observar essa informaÃ§Ã£o tambÃ©m em um balÃ£o verde logo acima do mesmo:

camilafernanda2/camilafernanda2 is a special repository: its README.md will appear on your profile!

TraduÃ§Ã£o: camilafernanda2/camilafernanda2 Ã© um repositÃ³rio especial: seu README.md aparecerÃ¡ em seu perfil!

Documento README.md do repositÃ³rio camilafernanda2/camilafernanda2 com o balÃ£o em verde no topo, como citado anteriormente, e com o texto em Markdown citado acima.
Note que com esse documento padrÃ£o, no seu perfil jÃ¡ irÃ¡ aparecer Hi there ğŸ‘‹, mas nÃ£o aparece o restante das sugestÃµes por elas estarem comentadas ao situar entre <! -- e -->

E agora? O que colocar no arquivo?
Gif do personagem animado Bob Esponja, que Ã© uma esponja amarela e quadrada que vive no fundo do mar. Ele Ã© personificado, portanto, possui braÃ§os e expressÃµes faciais. Sendo assim, no gif ele estÃ¡ com os olhos semicerrados, lÃ­ngua para fora, segurando um lÃ¡pis batendo na cabeÃ§a e ao mesmo tempo um bloco de anotaÃ§Ãµes, expressando estar pensando para escrever.
Ã€s vezes Ã© difÃ­cil se apresentar e escrever coisas sobre nÃ³s, nÃ£o Ã© mesmo? Mas segue algumas dicas do que vocÃª pode colocar no seu README:

Seu nome e um cumprimento bacana
A primeira coisa que falamos quando vamos nos apresentar geralmente Ã© uma saudaÃ§Ã£o e nosso nome, entÃ£o comece por isso. Segue alguns exemplos:

# OlÃ¡, me chamo SeuNomeAqui ! 
## Bem vindo ao meu perfil GitHub ğŸ‘‹
Ou

# SeuNomeAqui
## Hello, Devs!!
Ou aposte no inglÃªs, caso queira:

# ğŸ‘‹ Hello! Welcome to my Github profile.
## My name is SeuNomeAqui and my nickname is "SeuApelidoAqui"!
Fale um pouco sobre vocÃª
Fale sobre coisas que vocÃª ache essencial para que as pessoas que passarem pelo seu perfil do GitHub vejam. Seguem algumas coisas que particularmente gosto de demonstrar, mas Ã© totalmente opcional:

Se vocÃª trabalha ou estuda. Se sim, Ã© legal citar onde e em qual Ã¡rea;
O que vocÃª anda aprendendo;
Suas experiÃªncias, caso tenha, como atividades acadÃªmicas ou antigos trabalhos. Caso esteja em transiÃ§Ã£o de carreira, acredito que seja legal citar tambÃ©m;
Contatos, mas Ã© importante pensar direitinho quais colocarem;
Conhecimentos adquiridos;
RegiÃ£o onde mora, mas nÃ£o especifique tanto;
Entre outros, coloque apenas o que vocÃª se sentir confortÃ¡vel para colocar.
Nessa etapa, vocÃª pode colocar em forma de texto mesmo ou em tÃ³picos e com emojis, como o prÃ³prio GitHub sugere:

- ğŸ”­ Atualmente estou trabalhando em ...
- ğŸŒ± Atualmente estou aprendendo ...
- ğŸ‘¯ Estou procurando colaborar em ...
- ğŸ¤” Estou procurando ajuda com ...
- ğŸ’¬ Pergunte-me sobre ...
- ğŸ“« Como entrar em contato comigo: ...
- ğŸ˜„ Pronomes: ...
- âš¡ Curiosidade: ...
Para encontrar mais emojis, dÃª uma olhadinha nesse Gist do Rafael Xavier de Souza.

Tecnologias e Ferramentas
Para colocar seus conhecimentos adquiridos sobre tecnologias e ferramentas, vocÃª pode utilizar os logos das mesmas para tornar o perfil mais atrativo.

O Devicon Ã© uma ferramenta excelente para te auxiliar nisso, pois nele Ã© possÃ­vel encontrar Ã­cones de diversas tecnologias e ferramentas, atreladas a seu respectivo cÃ³digo em html para utilizar. Como o README aceita tags em HTML, vocÃª pode colÃ¡-las no seu arquivo.

Por exemplo, ao escolher o Ã­cone do Git, irÃ¡ surgir na barra esquerda versÃµes em SVG com suas tags <img loading="lazy">. Sendo assim, vocÃª pode copiÃ¡-las e colar no seu arquivo README escolhendo o tamanho com height e width.

Tela do Devicon com uma listagem de Ã­cones Ã  direita com um fundo branco, onde estÃ¡ selecionado o Ã­cone do Git. E Ã  esquerda, com fundo verde, estÃ£o versÃµes font e SVG com seus respectivos cÃ³digos, sendo em destaque o cÃ³digo da tag <img loading="lazy"> da primeira versÃ£o SVG da lista.
Dessa forma:

## Ferramentas e Tecnologias

<img loading="lazy" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" width="40" height="40"/>
Resultado:

Fundo branco com o tÃ­tulo â€œFerramentas e Tecnologiasâ€, seguido do Ã­cone do Git em laranja.
Assim por diante, vocÃª pode ir adicionando outros Ã­cones na frente. E alÃ©m disso, caso queira, vocÃª pode inserir as tecnologias e ferramentas que estÃ¡ estudando. Um exemplo:

## Estou aprendendo

<img loading="lazy" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" width="40" height="40"/> <img loading="lazy" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg" width="40" height="40"/>
Resultado:

Fundo branco com o tÃ­tulo â€œEstou aprendendoâ€, seguido dos Ã­cones do Java (uma xÃ­cara de cafÃ©) e do Linux (pinguim).
Contatos
Para que as pessoas que visitarem seu perfil no GitHub entrem em contato com vocÃª, Ã© interessante colocar suas redes sociais, principalmente se vocÃª produz conteÃºdos, pois assim Ã© possÃ­vel divulgar seu trabalho.

Para isso, vocÃª pode utilizar badges das suas redes sociais linkados para redirecionar os visitantes, exemplo:

## Contatos:

<div>
<a href="https://www.youtube.com/seu-canal-youtube-aqui" target="_blank"><img loading="lazy" src="https://img.shields.io/badge/YouTube-FF0000?style=for-the-badge&logo=youtube&logoColor=white" target="_blank"></a>
<a href="https://instagram.com/seu-usuÃ¡rio-instagram-aqui" target="_blank"><img loading="lazy" src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a>
<a href="https://www.twitch.tv/seu-usuÃ¡rio-aqui" target="_blank"><img loading="lazy" src="https://img.shields.io/badge/Twitch-9146FF?style=for-the-badge&logo=twitch&logoColor=white" target="_blank"></a>
<a href = "mailto:contato@seu-usuÃ¡rio-aqui"><img loading="lazy" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" target="_blank"></a>
<a href="https://www.linkedin.com/in/seu-usuÃ¡rio-linkedln-aqui" target="_blank"><img loading="lazy" src="https://img.shields.io/badge/-LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a>   
</div>
Note que onde estÃ¡ seu-usuÃ¡rio-aqui no cÃ³digo, Ã© preciso colocar o seu nome de usuÃ¡rio para que seja redirecionado para sua rede social, caso contrÃ¡rio, pode dar erro.

Resultado:

Fundo branco com o tÃ­tulo â€œContatos:â€, seguido de diversas badges, sendo elas, Youtube com o Ã­cone do mesmo Ã  esquerda e fundo da badge em vermelho, Instagram com o Ã­cone de cÃ¢mera Ã  esquerda e fundo da badge em rosa, Twitch com o Ã­cone da mesma Ã  esquerda e fundo da badge em roxo, Gmail com Ã­cone de carta Ã  esquerda e fundo da badge em vermelho e, por fim, o Linkedln com o Ã­cone do mesmo Ã  esquerda com o fundo da badge azul.
EstatÃ­sticas GitHub
Com o repositÃ³rio GitHub Readme Stats, vocÃª consegue colocar quadros como esse contendo a porcentagem da quantidade de cada linguagem em seus repositÃ³rios e o total de stars, commits, pull requests (PRs), total de issues e contribuiÃ§Ãµes.

Dois quadros de estatÃ­sticas do GitHub, sendo o da esquerda â€œMost used Languagesâ€, com uma barra de porcentagens tendo como legenda: JavaScript 70,34%, Java 18,91%, C 5,02%, HTML 4,76% e CSS 0,96%. E o quadro da direita representa â€œCamila Fernandaâ€™s GitHub Statsâ€ sendo composto por um cÃ­rculo de porcentagem com A+ no interior, Ã  esquerda do quadro temos â€œTotal Stars Earned: 5, â€œTotal Commits: 133â€, â€œTotal PRs: 2â€, â€œTotal Issues: 0â€ e â€œContributed to: 2â€.
Como fazer:

<div>
<a href="https://github.com/seu-usuÃ¡rio-aqui">
<img loading="lazy" height="180em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=seu-usuÃ¡rio-aqui&layout=compact&langs_count=7&theme=dracula"/>
<img loading="lazy" height="180em" src="https://github-readme-stats.vercel.app/api?username=seu-usuÃ¡rio-aqui&show_icons=true&theme=dracula&include_all_commits=true&count_private=true"/>
</div>
Note que onde estÃ¡ seu-usuÃ¡rio-aqui no cÃ³digo, Ã© preciso colocar o seu nome de usuÃ¡rio do GitHub para que seja demonstrado suas estatÃ­sticas, caso contrÃ¡rio, pode dar erro.

Gifs e imagens
Assim como a Alura Star Jeniffer Bittencourt, vocÃª tambÃ©m pode colocar gifs ou algum avatar que te represente.

Ela criou esse avatar com o Avatoon:

Avatar que representa a Jeniffer Bittencourt, que Ã© um personagem com camiseta vermelha, utilizando Ã³culos, cabelo castanho em penteado de coque, com uma expressÃ£o feliz acenando com a mÃ£o direita.
Mas caso queira, vocÃª pode criar seu Octocat tambÃ©m, que Ã© o sÃ­mbolo do GitHub personalizado para ficar a sua cara, como esse:

Octocat personalizado com cabelos longos cacheados, vestido amarelo, tÃªnis all star e segurando uma caneca branca com o sÃ­mbolo do GitHub, o octocat original.
E alÃ©m disso, vocÃª pode utilizar gifs como esse utilizado pela Jeniffer. Ã‰ um gatinho digitando que representa bem ela, pois ela ama gatos:

Gif de um gato cinza vestido de preto e azul sentado em um sofÃ¡ em frente Ã  uma mesa, onde tem um notebook que o mesmo estÃ¡ digitando extremamente rÃ¡pido.
VocÃª pode encontrar vÃ¡rios gifs no Tenor e colocar no seu repositÃ³rio.

AnimaÃ§Ã£o de cobrinha
Caso queira, vocÃª pode colocar uma animaÃ§Ã£o de uma cobrinha â€œcomendoâ€ suas contribuiÃ§Ãµes no grid, ela Ã© fornecida pelo repositÃ³rio snk e fica dessa forma no seu perfil:

Gif do grid de contribuiÃ§Ãµes do GitHub, ele Ã© composto por diversos quadrados pretos empilhados, onde os dias em que houve contribuiÃ§Ãµes, ficam em cor verde. No gif uma cobrinha formada pelos mesmos quadrados, porÃ©m de cor roxa, vai passando por todo o grid sumindo com os quadrados em verde, como se estivesse comendo-os.
Para implementar ela, primeiro coloque o seguinte cÃ³digo no seu arquivo README.md:

![Snake animation](https://github.com/seu-usuÃ¡rio-aqui/seu-usuÃ¡rio-aqui/blob/output/github-contribution-grid-snake.svg)
Note que onde estÃ¡ seu-usuÃ¡rio-aqui no cÃ³digo, Ã© preciso colocar o seu nome de usuÃ¡rio do GitHub para que seja demonstrado seu grid de contribuiÃ§Ãµes, caso contrÃ¡rio, pode dar erro.

Em seguida, vÃ¡ em Actions e selecione set up a workflow yourself â†’

Tela do repositÃ³rio camilafernanda2/camilafernanda2 no GitHub, onde estÃ¡ em destaque com o nÃºmero 1 a opÃ§Ã£o Actions na barra superior ao arquivo. E com o nÃºmero 2, estÃ¡ em destaque o texto em azul â€œset up a workflow yourself â†’â€.
E cole o seguinte cÃ³digo no editor de texto que irÃ¡ abrir:

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: andrewsga89
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
